"""empty message

Revision ID: 502ce4c7b2e1
Revises: d629ddb5a9e5
Create Date: 2022-08-11 12:16:34.194829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502ce4c7b2e1'
down_revision = 'd629ddb5a9e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
